### ISSUE TITLE
Support remotes in auto fetch exclusions

### ISSUE THREAD

**Issue by gberche-orange** [zielu/GitToolBox#168]
As a user, in order to avoid being prompted from flkky remotes during autofetch, I need to exclude some remotes from autofetch.

### Context: 

I have a git clone with 5 different remotes. One of them is flaky and most often refuses fetch requests from autofetch (with a 401), triggering a popup to validate git credentials.

I'd like to keep this remote in my git clone as I often need to manually perform git fetch on this remote (when its reacheable or I'm given permission)

The current auto fetch exclusion seems to support only submodules exclusions (as discussed in #59)
![image](https://user-images.githubusercontent.com/4748380/65768007-f6b0b880-e12f-11e9-90e2-03934405932d.png)

**Comment by zielu** [comment]
I think I will extend it to allow adding remotes under repo

**Comment by zielu** [comment]
@gberche-orange released to EAP channel in 192.3.1.
If you are willing to try it out see: https://github.com/zielu/GitToolBox#eap-builds about how to switch to EAP.

**Comment by zielu** [comment]
Done in 192.4.0

**Comment by gberche-orange** [comment]
thanks a lot @zielu for working on this feature, and sorry for late feedback. 

I am however unable to add a remote auto fetch exclusion. Are the remotes supposed to be listed in the autofetch exclusion list dialog?

I have some remotes configured
![image](https://user-images.githubusercontent.com/4748380/66734276-b6a54180-ee62-11e9-82db-99b108177019.png)

However, trying to add autofetch exclusions, I still only see submodules
![image](https://user-images.githubusercontent.com/4748380/66734315-e2282c00-ee62-11e9-9be2-98ded75b2547.png)

I'm running 192.4.0 with IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019

![image](https://user-images.githubusercontent.com/4748380/66734327-f8ce8300-ee62-11e9-906f-4461adb2b78e.png)

**Comment by zielu** [comment]
After repo is added you select it and then add button let's you add remotes to skip

**Comment by gberche-orange** [comment]
@zielu thanks

I'm however still unable to trigger this:  Here are the steps I followed:
1- Click add exclusion 
2- Select the current repo (which has several remotes as showed in https://github.com/zielu/GitToolBox/issues/168#issuecomment-541528590) and click OK
![image](https://user-images.githubusercontent.com/4748380/67015309-a4dbcc80-f0f6-11e9-8e90-7bcf98828f36.png)

=> did not show a dialog to select remote to exclude.
![image](https://user-images.githubusercontent.com/4748380/67015560-fbe1a180-f0f6-11e9-95f8-d4831b652273.png)

**Comment by zielu** [comment]
You need to click add exclusion one more time with repo selected.

It may make sense to combine everything into one dialog

**Comment by gberche-orange** [comment]
thanks @zielu !

One confirmation, if no remote are added, would all remotes be excluded or none be excluded ?

Here are screenshots below for others users that may need this hint.

![image](https://user-images.githubusercontent.com/4748380/67018481-99d76b00-f0fb-11e9-8adf-41dc4d0a7fde.png)

![image](https://user-images.githubusercontent.com/4748380/67018527-a956b400-f0fb-11e9-83e1-4f218baaec03.png)


![image](https://user-images.githubusercontent.com/4748380/67018421-82987d80-f0fb-11e9-9bb2-c6cbae8d3573.png)

**Comment by zielu** [comment]
Yes if none are specified all are excluded. I will add the hint.

**Comment by wjdp** [comment]
Hey, came looking for this feature and found this issue. I would not have worked this out on my own without this thread. Might be nice to add some explainer text to the auto fetch tab?

**Comment by zielu** [comment]
Hi, in latest version there are dedicated buttons for remotes to avoid double function of same controls, but I agree it could be improved. Maybe context menu on repo node would help. Wdyt ?

**Comment by zielu** [comment]
Also there was a tooltip to indicate all remotes are excluded, but I'm going to add that information into the tree:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/464103/116615314-65bd4700-a93b-11eb-9502-01205efe15f6.png">

@wjdp does it make it clearer ?

**Comment by wjdp** [comment]
I think so yes.

The mental jump I failed to make is the list isn't flat. I clicked the plus and saw a list of git repos in the project and just assumed there was no support for remote exclusions, only repos.

**Comment by zielu** [comment]
I created new issue describing UI improvement to remove that mental jump #310

**Comment by Laffery** [comment]
I use the v212.9.9 plugin, it seems that the `Auto Fetch Exclusions` feature is deprecated, which is helpful in my opinion, would you like to pop up the feature online again?

**Comment by zielu** [comment]
@Laffery they are available as project-level setting now.
<img width="832" alt="image" src="https://user-images.githubusercontent.com/464103/200524775-02c5e2e8-614e-499c-a84c-ac7b4aa3b6d7.png">

**Comment by Laffery** [comment]
> @Laffery they are available as project-level setting now. <img alt="image" width="832" src="https://user-images.githubusercontent.com/464103/200524775-02c5e2e8-614e-499c-a84c-ac7b4aa3b6d7.png">

Ohh thanks very much!
