### ISSUE TITLE
Missing gitmoji completion in non-modal commit UI

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#355]
> 
> 
> Possible because #268 is done
![image](https://user-images.githubusercontent.com/16933298/140082819-671f2f9f-8d6e-4946-9bb7-48593807904a.png)

No completion in Commit dialog.
IDEA Version: 2021.2.3

_Originally posted by @scruel in https://github.com/zielu/GitToolBox/issues/220#issuecomment-959306369_

**Comment by zielu** [comment]
Done in 203/212.8.0

**Comment by scruel** [comment]
> 
> 
> Done in 203/212.8.0

Nice work! 🎉

**Comment by scruel** [comment]
Still not work, plugin version 212.8.1.

**Comment by zielu** [comment]
Just to double check - you do have it enabled in plugin settings, right ?

**Comment by scruel** [comment]
Yep, I enabled the plugin, and Git Status on status bar, have more than one files to commit, but there is nothing happened after typing ":tada:".
![image](https://user-images.githubusercontent.com/16933298/142395745-0d2028ae-2ce0-480e-b840-5bd8aa06b75f.png)

**Comment by zielu** [comment]
But is any file selected for actual commit in Commit window ?

**Comment by scruel** [comment]
> But is any file selected for actual commit in Commit window ?

Yep, tried select or not select both.

**Comment by zielu** [comment]
Which OS are you on ? - maybe it makes some difference.

**Comment by zielu** [comment]
I pushed out EAP build with additional logging. Switch to the EAP channel as described here https://github.com/zielu/GitToolBox#eap-builds and enable logging (https://github.com/zielu/GitToolBox/wiki/AdvancedManual#debug-logging) from '#zielu.gittoolbox.completion'

**Comment by scruel** [comment]
> 
> 
> Which OS are you on ? - maybe it makes some difference.

Windows 10 Pro

**Comment by scruel** [comment]
> 
> 
> I pushed out EAP build with additional logging. Switch to the EAP channel as described here https://github.com/zielu/GitToolBox#eap-builds and enable logging (https://github.com/zielu/GitToolBox/wiki/AdvancedManual#debug-logging) from `#zielu.gittoolbox.completion`

Sorry, it works, I forgot to re-enable the gitmoji completion function in settings.
![image](https://user-images.githubusercontent.com/16933298/142552207-9597095c-1982-4bec-8749-f79689107b2e.png)

**Comment by scruel** [comment]
But I still not have colors for gitmojis(like https://github.com/zielu/GitToolBox/issues/272#issuecomment-734332500 mentioned)
Uncheck "as unicode":
![GIF](https://user-images.githubusercontent.com/16933298/142553015-92b2cee2-3086-4715-8449-ae8ec151acfa.gif)

Check "as unicode":
![GIF2](https://user-images.githubusercontent.com/16933298/142553293-f7ccda57-119b-4827-b319-e737ead44bf6.gif)

**Comment by scruel** [comment]
The completion need press ↓ to select the first recommend gitmoji then press ENTER to confirm the choose, rather than just press ENTER.

**Comment by zielu** [comment]
Ok, I'll look into completion behavior. Non-unicode mode works as it should - it inserts a text marker that should be displayed as icon later. Display part is missing for inline blame as you already noticed.

**Comment by zielu** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/206779405-Code-Completion-Popup-Focus

**Comment by zielu** [comment]
Moving completion improvement to #365. Missing completion is solved

**Comment by scruel** [comment]
IntelliJ IDEA 2021.2.4 (Ultimate Edition)
Build #IU-212.5712.43, built on December 21, 2021
Runtime version: 11.0.13+8-b1504.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2016M
Cores: 8


Not work again on the latest version.
